language: java

jdk:
- oraclejdk8

env:
- $PROJECT_DIR=lecture03

script: cd $PROJECT_DIR && ./gradlew assemble && ./gradlew check

after_success:
- ./gradlew jacocoTestReport
- bash <(curl -s https://codecov.io/bash)
